version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'practica'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: ""
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laraveltam'
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
